// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN0Ukc_oIf8oEhiKAnOIT9QvJ0tLUjCME',
    appId: '1:855980298776:web:0777014792eb4d1829296d',
    messagingSenderId: '855980298776',
    projectId: 'nganbi-app',
    authDomain: 'nganbi-app.firebaseapp.com',
    storageBucket: 'nganbi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoY1O19eQAVzkqCEIHfRoBZ8prwDnq2k',
    appId: '1:855980298776:android:f460d34012c1a2af29296d',
    messagingSenderId: '855980298776',
    projectId: 'nganbi-app',
    storageBucket: 'nganbi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xX8pL2faytsVeGjRwehU5vHJJaVPzaM',
    appId: '1:855980298776:ios:2bd50301bc4f283429296d',
    messagingSenderId: '855980298776',
    projectId: 'nganbi-app',
    storageBucket: 'nganbi-app.firebasestorage.app',
    iosBundleId: 'com.forcen.nganbiApp',
  );
}
